{% set version="0.0.1b" %}
{% set tag="8bc171f" %}
about:
    home: https://github.com/nh13/bfx-qc-reporter
    license: MIT
    summary: Bioinformatics QC Reporting Tools.
package:
    name: bfx-qc-reporter
    version: {{ version }}
build:
  number: 0
  skip: false
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - bfx-qc-reporter=bfx_qc_reporter.__main__:main
source:
  fn: {{ tag }}.tar.gz
  url: https://github.com/nh13/bfx-qc-reporter/archive/{{ tag }}.tar.gz
  sha256: 692bb802a74afa9043c968fdce648a66d05f6f07c89be15b40c4af49f394bbb1
requirements:
  build:
    - python
    - setuptools
  run:
    - python
test:
  commands:
    - 'bfx-qc-reporter 2>&1 | grep "^usage:"'
